# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcffba1086a61c8a3b2396a36c89d778b91aeb0d3a2e469c51731f534148fb0fa93a5c96d7204bdb82a6ca04ab0079cc406b04e68d5743f2271947a1e0088f4a

test:
  secret_key_base: 8e789ed3a62e29f59826ba08f319ffb8f8ad7300f2eaccfbf03d94972880735e6a85888859d3d47e72388c1431a3e092da96eb1eb653c5a5a197e5d40af7345a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
